name: BP - Build & Deploy

env:
  AZURE_WEBAPP_NAME: bp-calculator-prashidi
  AZURE_WEBAPP_PACKAGE_PATH: "."
  DOTNET_VERSION: "9"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # DEPLOY IAC
      - name: Deploy IaC (Bicep)
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: templates/main.bicep
          parameters: >
            appServiceName=${{ env.AZURE_WEBAPP_NAME }}
            location=northeurope
            environment=${{ github.ref == 'refs/heads/staging' && 'staging' || 'production' }}

      # DEPLOY CODE TO STAGING SLOT
      - name: Deploy code to Staging Slot
        if: github.ref == 'refs/heads/staging'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "staging"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          package: myapp

      # DEPLOY CODE TO PRODUCTION
      - name: Deploy code to Production
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: myapp
